package theworldnews.database.news.interfaces;

import java.sql.Connection;
import java.util.List;

import theworldnews.database.news.objects.Article;

public interface DisplayQueriesInterface {

	/**
	 * 
	 * @param con
	 *            Connection from java.sql package
	 * @param id
	 *            field value in table newsarticles
	 * @return Article without content
	 */
	public Article getDisplayarticleById(Connection con, int id);

	/**
	 * 
	 * @param con
	 *            Connection from java.sql package
	 * @param id
	 *            field value in table newsarticles
	 * @return Article with content with the given id
	 */
	public Article getViewarticleById(Connection con, int id);

	/**
	 * 
	 * @param con
	 *            Connection from java.sql package
	 * @param number
	 *            number of Article objects requested in output
	 * @param type
	 *            articlegroup String value, defines the groups the objects
	 *            belong in
	 * @return List of n Article objects which belong to the groups defined by
	 *         type
	 */
	public List<Article> getDisplayarticlesByNumberAndType(Connection con,
			int number, String type);

	/**
	 * 
	 * @param con
	 *            Connection from java.sql package
	 * @param articlegroupid
	 *            value for an articlegroup String generated by
	 *            theworldnews.database.news.objects.ArticleGroupEncoding
	 * @return List of Article objects which belong to the given group
	 */
	public List<Article> getDisplayarticlesByArticlegroup(Connection con,
			int articlegroupid);

}
